### ISSUE TITLE
how to comute smatch？

### ISSUE THREAD

**Issue by Wangpeiyi9979** [xdqkid/S2S-AMR-Parser#3]
Hi,  thanks for your work,
following the READMD.md, I get some files.
Is `sent.amr.restore.final ` the final amr output? 
I find the AMR in this file is in the linear form, and what is the golden AMR file.
How can I get the smatch score?

**Comment by xdqkid** [comment]
Thank you for following my work.  ``*.restore.pruned.wiki.coref.all'' is the final amr output when evaluating. See https://github.com/RikVN/AMR for more details.

**Comment by Wangpeiyi9979** [comment]
Thanks for your patience!
