### ISSUE TITLE
How to train this model from scratch

### ISSUE THREAD

**Issue by Wangpeiyi9979** [xdqkid/S2S-AMR-Parser#4]
Hi, Thanks for your nice work.
However, I am struggled with training the model from scratch? Could you help me!!

**Comment by xdqkid** [comment]
Following https://github.com/RikVN/AMR and https://github.com/OpenNMT/OpenNMT-py, it is easy to reproduce baseline. Do not use fairseq with my parameter settings!!! You should pay more attention to the paper and the code details.
